on: 
  workflow_dispatch:

jobs:
  jop_1:
    runs-on: ubuntu-latest
    steps:
      - run: "echo jop ${{github.jop}}"

  jop_2:
    runs-on: ubuntu-latest
    needs: jop_1
    steps:
      - run: "echo jop ${{ github.jop}}"

  jop_3:
    runs-on: ubuntu-latest
    needs: jop_1
    steps:
      - run: "echo jop ${{ github.jop}}"

  jop_4:
    runs-on: ubuntu-latest
    needs: [ jop_2 , jop_3 ]
    steps:
      - run: "echo jop ${{ github.jop}}"
