name: first workflow
on:
   push:
        branches:
           -  main

jobs:
   example-jop:
     runs-on: ubuntu-latest

     steps:
        - name: print a welcome message
          run: echo "welcome"

        - name: Checkout repository
          uses: actions/checkout@v6.0.2

        - name: List repository files
          run: ls -la
  
