on:
   push:
     branches: 
       - main
       - dev
    #  path:
    #  - "src/**"
    pull:
      - main
jops:
  test:
    run-on:ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

      -name: Run-tests
       run: npm test
