on:
   push:
     branches: 
       - main
       - dev
    #  paths:
    #  - "src/**"
    pull_request:
      - main
jobs:
  test:
    runs-on:ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6.0.2

    - name: Run-tests
       run: npm test
